rango/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from rango import views

from rango import views

app_name='rango'#创建了命名空间
urlpatterns = [
     url(r'^about/$',views.about,name='about'),
     url(r'^show_category/(?P<category_name_slug>[\w\-]+)/$',views.show_category,name='show_category'),
     url(r'^add_category/$',views.add_category,name='add_category'),
     url(r'^add_page/(?P<category_name_slug>[\w\-]+)/$',views.add_page,name="add_page"),
     url(r'^search/$',views.search,name='search'),
     url(r'^like/$',views.like_category,name='like_category'),
     url(r'^suggestion/$',views.suggest_category,name="suggestion"),
]

rango_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    #下面的映射把以rango/开头的URL交给rango的应用处理
    url(r'^rango/',include('rango.urls')),
    #重写RegistrationView类。。如果把一个类作为视图，最后要写成 .as_view()方法
    url(r'^accounts/register/$', views.RangoRegistrationView.as_view(), name='registration_register'),

    #导入这个registration外部应用，它内部写好了视图函数，我们需要自己写模板
    url(r'^accounts/',include('registration.backends.simple.urls')),#引入 registration 包的URL 映射

    url(r'^users/',include('users.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

rango/models.py
from django.template.defaultfilters import slugify
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128,unique=True)
    views=models.IntegerField(default=0)
    likes=models.IntegerField(default=0)
    #“i like django”,通过下面的SlugField()类型设置将slug设置成"i-like-django"
    slug=models.SlugField(unique=True)#url路径类型，并且添加唯一性约束

    #使用save（）时候，调用此函数
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
         self.slug=slugify(self.name)
         super(Category,self).save()

    #下面的方法可以让对象变成字符串表示形式。。此外， Django 会在管理后台中显示对象的字符串表示形式。
    def __str__(self):
        return self.name

    # 改变admin管理系统中表单的名称
    class Meta:
        verbose_name_plural = 'Categories'

class Page(models.Model):
    category=models.ForeignKey('Category',on_delete=models.CASCADE)#会在数据表中增加这个外键字段。值为外键的id
    title=models.CharField(max_length=128)
    url=models.URLField()
    views=models.IntegerField(default=0)

    def __str__(self):
        return self.title

rango/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.urls import reverse
from registration.backends.simple.views import RegistrationView

from rango.models import Category,Page
from rango.form import  CategoryForm,PageForm
from rango.webhose_search import run_query


def get_server_side_cookie(request,cookie,default_val=None):
    #通过 requests.sessions.get() 检查 cookie 是否存在,因为request中有存放sessionid的cookie
    val=request.session.get(cookie)
    if not val:
        val=default_val
    return val

def visitor_cookie_handler(request):
    #获得或者创建一个cookie：visits,request.COOKIES.get这个方法获取的都会变成字符串类型
    visits=int(get_server_side_cookie(request,'visits','1'))
    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    #把last_visit变成Datetime类型
    last_visit_time=datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    #设置成连续10s内访问不增加数值
    if(datetime.now()-last_visit_time).seconds>=10:
        visits=visits+1
        request.session['last_visit']=str(datetime.now())
    else:
        request.session['last_visit']=last_visit_cookie

    request.session['visits']=visits


def index(request):

    #想要赋值使用字典的话，必须要先定义字典
    context_dict = {}
    #查询数据库，获取前5个分类，放入上下文变量中
    category_list=Category.objects.order_by('-views')[:5]
    #创建上下文字典，渲染模板
    context_dict['category_list'] =category_list

    page_list=Page.objects.order_by('-views')[:5]
    context_dict['page_list']=page_list

    #调用处理 cookie 的辅助函数
    visitor_cookie_handler(request)
    context_dict['visits']=request.session['visits']

    # render是生成一个response对象
    response = render(request, 'rango/index.html', context_dict)

    # 返回 response 对象，更新目标 cookie
    return response

def show_category(request,category_name_slug):
    context_dict={}
    category = Category.objects.get(slug=category_name_slug)
    context_dict["category"]=category
    try:
        pages=Page.objects.filter(category=category)
        context_dict["pages"]=pages
    except "page.doesnotexist":
        context_dict['pages']=None

    return render(request,'rango/category.html',context_dict)

def about(request):
    #html代码可以直接返回给浏览器，浏览器会进行解析。所以可以在python中写html代码，python把它当字符串处理，返回给浏览器后，浏览器会进行解析。
    # return HttpResponse("<hr>"+"<h2>关于</h2>"+"<hr>")
    return render(request,'rango/about.html',{})


@login_required
def add_category(request):
    #创建一个CategoryForm对象
    form = CategoryForm()
    #HTTP GET请求 获取指定资源的表述。即HTTP GET请求用于获取特定的资源,例如一个网页、一张图像或一个文件。
    #HTTP POST请求 向服务器中提交数据，一般还会存入数据库。
    #判断是不是HTTP POST请求，即是不是提交数据过来的，如果不是的话，则是首次访问页面过来添加数据的
    if request.method == "POST":
        #把数据放到CategoryForm中，生成一个新CategoryForm对象，名字还是form
        form=CategoryForm(request.POST)

        #表单数据有效吗？
        if form.is_valid():
            #调用save函数，会生成一个Category对象，并且将表单数据存到对象里，commit=True会把新分类对象存入数据库
            cat=form.save(commit=True)#通过表单创建一个对象
            #调用index（）函数，必须要有请求对象作为参数，把用户带到首页
            print(cat)
            return index(request)

        else:
            #表单数据有错误,在服务器的终端（控制台）里打印出来
            print(form.errors)
            return render(request, 'rango/add_category.html', {"form": form})

    return render(request,'rango/add_category.html',{"form":form})

@login_required
def add_page(request,category_name_slug):

    try:
        category=Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category=None

    form=PageForm()
    if request.method == "POST":
        form = PageForm(request.POST)

        if form.is_valid():
            ##Pageform调用save函数，会生成一个Page对象，并且将表单数据存到对象里，commit=False不会把表单数据存入数据库
            page=form.save(commit=False)
            page.category=category
            page.views=0
            page.save()
            return show_category(request,category_name_slug)
        else:
            print(form.errors)
            #context_dict = {"form": form, "category": category}
            #return render(request,"rango/add_page.html",context_dict)

    context_dict={"form":form,"category":category}
    return render(request,"rango/add_page.html",context_dict)


#RangoRegistrationView类继承了RegistrationView，并且重写了get_success_url方法
class RangoRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('index')

def search(request):
    result_list=[]
    query_str=""
    if request.method == "POST":
        query_str=request.POST['query'].strip()
        if query_str:
            result_list=run_query(query_str)

    return render(request,"rango/search.html",{"result_list":result_list,"query_str":query_str})

@login_required
def like_category(request):
    cat_id = None
    print("怎么回事儿")

    if request.method == "GET":
        cat_id = request.GET['category_id']
    likes = 0
    if cat_id:
        cat =Category.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes+1
            cat.likes = likes
            cat.save()
    return HttpResponse(likes)

def get_category_list(max_results=0,starts_with=""):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results>0:
        if len(cat_list)>max_results:
            cat_list=cat_list[:max_results]
    return cat_list


def suggest_category(request):
    cat_list = []
    starts_with = ""

    if request.method == "GET":
        starts_with = request.GET['suggestion']
    cat_list=get_category_list(8,starts_with)
    #render生成一个response对象，这个响应对象是经过数据渲染过的html代码。
    # 然后return返回给向这个函数发送请求的对象，可能是浏览器，可能是ajax请求
    return render(request,'rango/cats.html',{'cats':cat_list})

templates/rango/about.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    关于
{% endblock %}
{% block body_block %}

    <div id="msg">Hello - I'm here for a JQuery Example too</div>
    <br>
    <button id="about-btn" class="btn btn-primary" >
           点击我
    </button>

{% endblock %}

templates/rango/add_category.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    添加分类
{% endblock %}
{% block body_block %}
    <div>
           <form id="category_form" method="post" action="{% url "rango:add_category" %}">
              <!-- Django使用模板标签{% csrf_token %}来防止攻击者利用表单来获得对服务器未经授权的访问-->
               {% csrf_token %}
               <!--我们显示表单， 从中可知Django使得完成显示表单等任务有多简单：
                我们只需包含模板变量{{ form.as_p }} ， 就可让Django自动创建显示表单所需的全部字段。
                 修饰符as_p 让Django以段落格式渲染所有表单元素， 这是一种整洁地显示表单的简单方式。-->
               {{ form.as_p }}
               <button class="btn btn-primary" type="submit" name="submit">添加</button>
           </form>
       </div>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    添加页面
{% endblock %}
{% block body_block %}
    {{ category }}
<form id="page_form" action="{% url "rango:add_page" category.slug %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
 <button class="btn btn-primary" type="submit" name="submit">添加</button>
</form>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}

{% load rango_template_tags %}
<!-- 使用bootstrap框架，首先要换：
1.把所有 ../../ 路径替换为 http://v4-alpha.getbootstrap.com/。
2.把 dashboard.css 的路径替换为绝对地址： http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css。
-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

  <!--网站小图标,放置在title的前面-->
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>
        {% block title_block %}
            Rango
        {% endblock %}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">



  </head>

  <body>
  <!-- 顶部导航栏-->
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url "index" %}">Tango</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item active">
            <a class="nav-link" href="{% url "index" %}">首页 <span class="sr-only">(current)</span></a>
          </li>
         {% if user.is_authenticated %}
              <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:search' %}">搜索</a>
             </li>
             <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_logout' %}">注销</a>
             </li>
         {% else %}
              <li class="nav-item">
            <a class="nav-link" href="{% url "registration_register" %}">注册</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "auth_login" %}">登录</a>
          </li>
        {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "rango:about" %}">关于</a>
          </li>
        </ul>

      </div>
    </nav>

  <!-- 主内容区域：两个div标签，放置sidebar_block和body_block区块-->
    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <li class="nav-item">最受欢迎的8个分类：</li>
            {% block sidebar_block %}
                {% get_category_list category%}<!-- category参数可以为none，有的话再传 -->
             {% endblock %}

             <ul class="nav nav-list flex-column">
            <li class="nav-item">搜索分类：</li>
            <form>
            <li class="nav-item"><input class="search-query form-control" type="text"
            name="suggestion" value="" id="suggestion" />
            </li>
            </form>
            </ul>
            <hr>
            <div id="cats">
            </div>
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
             {% block body_block %}
                 default content
            {% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
   <!--引入jquery库-->
      <script src="{% static 'js/rango-jquery.js' %}"></script>
    <!--引入我们自己写的jquery和ajax文件-->
  <script src="https://cdn.staticfile.org/jquery/3.0.0/jquery.min.js"></script>
   <script src="{% static 'js/rango-ajax.js' %}"></script>

  </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
<!-- 用到静态文件的每个模板都要在文件顶部添加{% load staticfiles %}。
  否则会导致错误！-->
{% load staticfiles %}

{% block title_block %}
   分类：{{ category.name }}
{% endblock %}

{% block body_block %}
    {% if pages %}
    <ul>
    {% for page in pages %}
    <li>
        <a href="{{ page.url }}">{{ page.title }}</a>
    </li>
    {% endfor %}
    </ul>
    {% else %}
         <strong>当前分类下没有页面</strong>
    {% endif %}

    <div>
    <strong id="like_count">{{category.likes}}</strong>人喜欢这个分类
    {% if  user.is_authenticated %}
        <button id="likes" data-catid="{{category.id}}" class="btn btn-primary btn-sm"  type="button">
        喜欢
        </button>
        <br>
        <a href="{% url "rango:add_page"  category.slug%}">添加页面</a>
    {% endif %}
    </div>


{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <strong>
                 <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a> </li>
                </strong>
            {% else %}
            <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a> </li>
            {% endif %}
        {% endfor %}
    {% else %}
         <li><strong>目前还没有分类</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Rango应用
{% endblock %}
{% block body_block %}
     <!-- Custom styles for this template -->
 <link href="https://getbootstrap.com/docs/4.0/examples/narrow-jumbotron.css" rel="stylesheet">

      <div>
           <img src="{% static "images/Tango.jpg" %} "  alt="picture of Rango"/>
       </div>

    <h4>您访问了{{ visits }}次</h4>
     <div class="row marketing">
        <div class="col-lg-6">
          <h4> 访问最多的5个分类:</h4>
         {% if category_list %}
             <ul>
                 {% for category in category_list %}
                  <li><p><a href="{% url "rango:show_category" category.slug %}">{{ category.name }}</a></p></li>
                  {% endfor %}
             </ul>
         {% else %}
             <p>目前没有分类</p>
         {% endif %}

         {% if user.is_authenticated %}
           <p><a href="{% url "rango:add_category" %}">添加分类</a></p>
         {% endif %}


        </div>

        <div class="col-lg-6">

            {% if page_list %}
             <h4>访问最多的5个页面:</h4>
             <ul>
                 {% for page in page_list %}
                  <li><p><a href="{{page.url}}">{{ page.title}}</a></p></li>
                  {% endfor %}
             </ul>
         {% else %}
             <p>目前没有页面</p>
         {% endif %}

        </div>
      </div>

{% endblock %}

templates/rango/search.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    查询
{% endblock %}
{% block body_block %}
    <div>
        <form class="form-inline" method="post" action="{% url "rango:search" %}">
            {% csrf_token %}
            <input class="form-control" type="text" size="50" name="query" value="{{ query_str }}" id="query" />
            <button class="btn btn-primary" type="submit" name="submit">搜索</button>
        </form>
    </div>
    <div>
        {% if result_list %}
        <h3>搜索结果：</h3>
        <!-- 按顺序显示搜索结果,result_list里面是列表，列表的每一项里都是字典 -->
        <div class="list-group">
            {% for result in result_list %}
            <div class="list-group-item">
                 <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
                <p class="list-group-item-text">{{ result.summary }}</p>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock %}